-- Auto-generated by notebooks/01_eda.ipynb (Day 3).
-- Per-feature summary statistics for f0..f11.
-- Run from project root: duckdb data/criteo.duckdb < sql/02_eda_features.sql

SELECT
    'f0' AS feature_name,
    MIN(f0)                             AS min_val,
    MAX(f0)                             AS max_val,
    AVG(f0)                             AS mean_val,
    STDDEV(f0)                          AS std_val,
    quantile_cont(f0, 0.10)             AS p10,
    quantile_cont(f0, 0.25)             AS p25,
    quantile_cont(f0, 0.50)             AS p50,
    quantile_cont(f0, 0.75)             AS p75,
    quantile_cont(f0, 0.90)             AS p90,
    quantile_cont(f0, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f1' AS feature_name,
    MIN(f1)                             AS min_val,
    MAX(f1)                             AS max_val,
    AVG(f1)                             AS mean_val,
    STDDEV(f1)                          AS std_val,
    quantile_cont(f1, 0.10)             AS p10,
    quantile_cont(f1, 0.25)             AS p25,
    quantile_cont(f1, 0.50)             AS p50,
    quantile_cont(f1, 0.75)             AS p75,
    quantile_cont(f1, 0.90)             AS p90,
    quantile_cont(f1, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f2' AS feature_name,
    MIN(f2)                             AS min_val,
    MAX(f2)                             AS max_val,
    AVG(f2)                             AS mean_val,
    STDDEV(f2)                          AS std_val,
    quantile_cont(f2, 0.10)             AS p10,
    quantile_cont(f2, 0.25)             AS p25,
    quantile_cont(f2, 0.50)             AS p50,
    quantile_cont(f2, 0.75)             AS p75,
    quantile_cont(f2, 0.90)             AS p90,
    quantile_cont(f2, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f3' AS feature_name,
    MIN(f3)                             AS min_val,
    MAX(f3)                             AS max_val,
    AVG(f3)                             AS mean_val,
    STDDEV(f3)                          AS std_val,
    quantile_cont(f3, 0.10)             AS p10,
    quantile_cont(f3, 0.25)             AS p25,
    quantile_cont(f3, 0.50)             AS p50,
    quantile_cont(f3, 0.75)             AS p75,
    quantile_cont(f3, 0.90)             AS p90,
    quantile_cont(f3, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f4' AS feature_name,
    MIN(f4)                             AS min_val,
    MAX(f4)                             AS max_val,
    AVG(f4)                             AS mean_val,
    STDDEV(f4)                          AS std_val,
    quantile_cont(f4, 0.10)             AS p10,
    quantile_cont(f4, 0.25)             AS p25,
    quantile_cont(f4, 0.50)             AS p50,
    quantile_cont(f4, 0.75)             AS p75,
    quantile_cont(f4, 0.90)             AS p90,
    quantile_cont(f4, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f5' AS feature_name,
    MIN(f5)                             AS min_val,
    MAX(f5)                             AS max_val,
    AVG(f5)                             AS mean_val,
    STDDEV(f5)                          AS std_val,
    quantile_cont(f5, 0.10)             AS p10,
    quantile_cont(f5, 0.25)             AS p25,
    quantile_cont(f5, 0.50)             AS p50,
    quantile_cont(f5, 0.75)             AS p75,
    quantile_cont(f5, 0.90)             AS p90,
    quantile_cont(f5, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f6' AS feature_name,
    MIN(f6)                             AS min_val,
    MAX(f6)                             AS max_val,
    AVG(f6)                             AS mean_val,
    STDDEV(f6)                          AS std_val,
    quantile_cont(f6, 0.10)             AS p10,
    quantile_cont(f6, 0.25)             AS p25,
    quantile_cont(f6, 0.50)             AS p50,
    quantile_cont(f6, 0.75)             AS p75,
    quantile_cont(f6, 0.90)             AS p90,
    quantile_cont(f6, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f7' AS feature_name,
    MIN(f7)                             AS min_val,
    MAX(f7)                             AS max_val,
    AVG(f7)                             AS mean_val,
    STDDEV(f7)                          AS std_val,
    quantile_cont(f7, 0.10)             AS p10,
    quantile_cont(f7, 0.25)             AS p25,
    quantile_cont(f7, 0.50)             AS p50,
    quantile_cont(f7, 0.75)             AS p75,
    quantile_cont(f7, 0.90)             AS p90,
    quantile_cont(f7, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f8' AS feature_name,
    MIN(f8)                             AS min_val,
    MAX(f8)                             AS max_val,
    AVG(f8)                             AS mean_val,
    STDDEV(f8)                          AS std_val,
    quantile_cont(f8, 0.10)             AS p10,
    quantile_cont(f8, 0.25)             AS p25,
    quantile_cont(f8, 0.50)             AS p50,
    quantile_cont(f8, 0.75)             AS p75,
    quantile_cont(f8, 0.90)             AS p90,
    quantile_cont(f8, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f9' AS feature_name,
    MIN(f9)                             AS min_val,
    MAX(f9)                             AS max_val,
    AVG(f9)                             AS mean_val,
    STDDEV(f9)                          AS std_val,
    quantile_cont(f9, 0.10)             AS p10,
    quantile_cont(f9, 0.25)             AS p25,
    quantile_cont(f9, 0.50)             AS p50,
    quantile_cont(f9, 0.75)             AS p75,
    quantile_cont(f9, 0.90)             AS p90,
    quantile_cont(f9, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f10' AS feature_name,
    MIN(f10)                             AS min_val,
    MAX(f10)                             AS max_val,
    AVG(f10)                             AS mean_val,
    STDDEV(f10)                          AS std_val,
    quantile_cont(f10, 0.10)             AS p10,
    quantile_cont(f10, 0.25)             AS p25,
    quantile_cont(f10, 0.50)             AS p50,
    quantile_cont(f10, 0.75)             AS p75,
    quantile_cont(f10, 0.90)             AS p90,
    quantile_cont(f10, 0.99)             AS p99
FROM criteo
UNION ALL
SELECT
    'f11' AS feature_name,
    MIN(f11)                             AS min_val,
    MAX(f11)                             AS max_val,
    AVG(f11)                             AS mean_val,
    STDDEV(f11)                          AS std_val,
    quantile_cont(f11, 0.10)             AS p10,
    quantile_cont(f11, 0.25)             AS p25,
    quantile_cont(f11, 0.50)             AS p50,
    quantile_cont(f11, 0.75)             AS p75,
    quantile_cont(f11, 0.90)             AS p90,
    quantile_cont(f11, 0.99)             AS p99
FROM criteo
ORDER BY feature_name;
