-- Auto-generated by notebooks/02_experimentation.ipynb (Day 5).
-- Quartile-bucketed lift per feature for heterogeneity analysis.
-- One row per (feature, bucket, treatment). Pivot in pandas to get
-- per-bucket lift = treatment_rate - control_rate.
-- Run from project root: duckdb data/criteo.duckdb < sql/04_heterogeneity.sql

SELECT
    'f0' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f0) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f1' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f1) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f2' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f2) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f3' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f3) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f4' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f4) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f5' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f5) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f6' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f6) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f7' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f7) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f8' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f8) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f9' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f9) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f10' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f10) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
UNION ALL
SELECT
    'f11' AS feature_name,
    bucket,
    treatment,
    AVG(conversion)        AS rate,
    COUNT(*)               AS n,
    SUM(conversion)        AS conversions
FROM (
    SELECT
        conversion,
        treatment,
        NTILE(4) OVER (ORDER BY f11) AS bucket
    FROM criteo
)
GROUP BY bucket, treatment
ORDER BY feature_name, bucket, treatment;
